/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jamie
 */
public class Bookings extends javax.swing.JFrame {

    /**
     * Creates new form Bookings
     */
    public Bookings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bookingslbl = new javax.swing.JLabel();
        BackToMenubtn = new javax.swing.JButton();
        AddBookingbtn = new javax.swing.JButton();
        ViewBookingbtn = new javax.swing.JButton();
        DeleteBookingbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        Bookingslbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Bookingslbl.setText("BOOKINGS");

        BackToMenubtn.setText("Back To Main Menu");
        BackToMenubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenubtnActionPerformed(evt);
            }
        });

        AddBookingbtn.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        AddBookingbtn.setText("ADD BOOKING");
        AddBookingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookingbtnActionPerformed(evt);
            }
        });

        ViewBookingbtn.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        ViewBookingbtn.setText("VIEW BOOKING");
        ViewBookingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBookingbtnActionPerformed(evt);
            }
        });

        DeleteBookingbtn.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        DeleteBookingbtn.setText("DELETE BOOKING");
        DeleteBookingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBookingbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackToMenubtn)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bookingslbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(AddBookingbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(ViewBookingbtn)
                .addGap(67, 67, 67)
                .addComponent(DeleteBookingbtn)
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bookingslbl)
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeleteBookingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ViewBookingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AddBookingbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(BackToMenubtn)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToMenubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenubtnActionPerformed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(() -> {
            new RoomBookingForm().setVisible(true);
        });
    }//GEN-LAST:event_BackToMenubtnActionPerformed

    private void AddBookingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookingbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(() -> {
            new AddBooking().setVisible(true);
        });
    }//GEN-LAST:event_AddBookingbtnActionPerformed

    private void ViewBookingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBookingbtnActionPerformed
        // TODO add your handling code here:
         dispose();
        java.awt.EventQueue.invokeLater(() -> {
            new ViewBooking().setVisible(true);
         });
         
    }//GEN-LAST:event_ViewBookingbtnActionPerformed

    private void DeleteBookingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBookingbtnActionPerformed
        // TODO add your handling code here:
         dispose();
        java.awt.EventQueue.invokeLater(() -> {
            new DeleteBooking().setVisible(true);
         });
    }//GEN-LAST:event_DeleteBookingbtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBookingbtn;
    private javax.swing.JButton BackToMenubtn;
    private javax.swing.JLabel Bookingslbl;
    private javax.swing.JButton DeleteBookingbtn;
    private javax.swing.JButton ViewBookingbtn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
